language: ruby
rvm:
- ruby-head
deploy:
  provider: heroku
  app: commonplaces-app
  api_key:
    secure: o3QIb6Vdu/tKl+mL99oCPJlqNAOoQVKmSdtMe4IF0Fnxi5NAc4OxL4bIjkf1fz2VO/1otRYkFoDcrtZbsDGJsf62xzIUbbtHNMDoeynMgd8ZRD4JYnAlm6riNtfIeyYrIEw/6OxY6fWyjpkmO839FZR3aO9KTXCGoqAOxuWvbZcSFHNoTMUjbzZm1tzwrn9T+JkAdRdFtTDZFi13HgblVe9VGkvV0eND/yMUXBhG6NLHDbKG4la77uOMPJTziHVzQ/160qzQNmv0X4tqgCdsj10XsrcqX4Bse+Tlb559qaGzYHu+NMdkYPmSPzGyWgZtZEQdPS6blttq0ZGpmhCUq5QbZnU0GCG/DE5u+AxwHZKoa+vC1pmVuyuRjmjpKruNMFl7BWqQ++e29E0siZ7qJC033lUD/zBJHmCRd3CMMRo+bkhvGtyL8SGxmaohnP5+86hRrPeiJ22isxPbDam6tx6s8VrlZ+OZoaB46XvHRby8Pjxq42s73ztlElc82RO4mdveZ1tWCnKAuvto9yPsxz6BoBJHFT30eBjSxkcCNUPr7MrwbLEv2G5/DfXwOuzGXLkdg/QRXgFpZ4gW6dW2gSoZjJEQC2sJiM3SvgRvjC5tZKaVb+8NDKWZN1mx9X10t0Q63KhXLX7ndlPMvH9jsX+7Ynx9yOPuHIjSXTS3nZM=
